[package]
name = "vapor-platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
notify = "=8.2.0"
vapor-shared = { path = "../shared" }

[target.'cfg(unix)'.dependencies]
libc = "=0.2.183"
signal-hook = "=0.3.18"
xattr = "=1.6.1"

[dev-dependencies]
tempfile = "=3.27.0"

[lib]
path = "src/lib.rs"
