[package]
name = "vapor-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "=4.5.50", features = ["derive"] }
serde = { workspace = true }
serde_json = { workspace = true }
vapor-daemon = { path = "../daemon" }
vapor-ipc = { path = "../ipc" }
vapor-lifecycle = { path = "../lifecycle" }
vapor-platform = { path = "../platform" }
vapor-providers = { path = "../providers" }
vapor-shared = { path = "../shared" }

[target.'cfg(unix)'.dependencies]
libc = "=0.2.183"

[dev-dependencies]
tempfile = { workspace = true }

[lib]
path = "src/lib.rs"

[[bin]]
name = "vapor"
path = "src/main.rs"
